<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeRepository extends EntityRepository {

    public function findAllArray() {
        return $this->createQueryBuilder('g')
            ->getQuery()
            ->getArrayResult()
        ;
    }
}
