<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonRepository extends EntityRepository {

    public function findAllArray() {
        return $this->createQueryBuilder('l')
            ->getQuery()
            ->getArrayResult()
        ;
    }
}
