security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: email
        in_memory:
            memory:
                users:
                    admin:  { password: admin, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: security_login
                check_path: login_check
                default_target_path: back_index
            logout:
                path:   /logout
                target: front_home

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
